### PR TITLE
🐛 fix ginkgo version mismatch

### PR DESCRIPTION
**Pull request by kranurag7**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Review by guettli — CHANGES_REQUESTED** [review]
Hi Anurag, unfortunately there is still a version mismatch:

If I look at the e2e hcloud test, then I see in the raw logs this:


```
2024-01-16T15:11:44.2665871Z [38;5;9m[1mGinkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:[0m
2024-01-16T15:11:44.2667711Z   Ginkgo CLI Version:
2024-01-16T15:11:44.2668676Z     [1m2.7.1[0m
2024-01-16T15:11:44.2669174Z   Mismatched package versions found:
2024-01-16T15:11:44.2670013Z     [1m2.13.2[0m used by e2e

```

[raw logs of hcloud basic test](https://pipelinesghubeus26.actions.githubusercontent.com/21BXMMjxIP1jeQN0vb5oadH6da1GcLCd1chagFLgWbOKsn1XRg/_apis/pipelines/1/runs/18567/signedlogcontent/20?urlExpires=2024-01-31T10%3A12%3A20.0216459Z&urlSigningMethod=HMACV1&urlSignature=6CNSrVf9fnSYGpe1gQ%2FuYhzB40cxemis9K%2BnvnL%2FrC4%3D)

**Comment by kranurag7** [comment]
Thomas, Locally I'm not able to reproduce it. If you run the make test-e2e-baremetal or any e2e tests locally then we are not getting version mismatched.

**Comment by guettli** [comment]
> Thomas, Locally I'm not able to reproduce it. If you run the make test-e2e-baremetal or any e2e tests locally then we are not getting version mismatched.

@kranurag7 

I see. 

What does your change do? Does it solve that on your local device?

What can we do?

One thing which came to my mind: We could remove the actual tests in this PR (just for testing), so that the e2e finish immediately. This provides a better test-environment for you, because you don't need to wait that long.

Does this make sense to you, or do you have a different idea?

Overall it is not that important. But would be nice to have this fixed some day.

**Review by guettli — APPROVED** [review]
thank you!

**Pull request merged**
