### PR TITLE
🌱 Remove type-assertion for *prometheus.Registry in hcloud Client

### PR DESCRIPTION
**Pull request by apricote**
**What this PR does / why we need it**:

Starting from [v2.6.0](https://github.com/hetznercloud/hcloud-go/releases/tag/v2.6.0), hcloud-go accepts [`prometheus.Registerer` interface](https://github.com/hetznercloud/hcloud-go/pull/369), so the type-assertion workaround is no longer needed.

This PR requires a bump to hcloud-go v2.6.0+. I had some trouble with vendoring locally, so I wanted to let renovate do its job.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Comment by kranurag7** [comment]
Hey Julian, 
Thanks for the patch. It looks good to me from my end. 
For vendoring, I checked the PR locally and did the following. 

```bash
go get -u  github.com/hetznercloud/hcloud-go/v2@v2.6.0 
make generate-modules 
make test-unit
```
Units tests passed for me locally and build as well. Wondering if I'm missing something above because I'm sure you must have done the same on your end.

**Comment by apricote** [comment]
Thanks for the commands, worked today after cleaning up the repo. No idea what I did yesterday, `go mod` was complaining about incompatible dependencies.

**Review by janiskemper — APPROVED** [review]

**Comment by janiskemper** [comment]
can you rebase this @apricote? Just saw that you have two commits

**Comment by apricote** [comment]
For sure, just squash the 2 commits?

**Comment by janiskemper** [comment]
yes

**Comment by kranurag7** [comment]
@apricote Please also rebase the commit on top of main. We made some changes in our e2e test config. 
Thank you.

**Comment by apricote** [comment]
Rebased and squashed ontop of current `main` :+1:

**Pull request merged**
