### PR TITLE
🌱 Update quickstart guide with upstream ccm

### LINKED ISSUE #1401: Docs about HCloud-only ccm in Quickstart are out-of-date
https://github.com/syself/cluster-api-provider-hetzner/blob/main/docs/caph/01-getting-started/02-quickstart/03-creating-a-workload-cluster.md?plain=1#L103

```
KUBECONFIG=$CAPH_WORKER_CLUSTER_KUBECONFIG helm upgrade --install ccm syself/ccm-hcloud --version 1.0.11 \
	--namespace kube-system \
	--set secret.name=hetzner \
	--set secret.tokenKeyName=hcloud \
	--set privateNetwork.enabled=false
```

We don't maintain the hcloud-ccm helm chart anymore. We should use the upstream CCM instead.

Related: #1399, thanks for reporting @madbbb

### PR DESCRIPTION
**Pull request by SD-13**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1401

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Comment by SD-13** [comment]
@janiskemper PTAL when you get time. Thanks!

**Comment by SD-13** [comment]
Looks like the lychee lint check is passing, but marking it as fail GitHub action.

**Comment by janiskemper** [comment]
@guettli can you review and check why the linting fails? Looks very weird. exit code 2 but no error is shown

**Comment by janiskemper** [comment]
thanks a lot @SD-13 for this PR btw ;)

**Comment by SD-13** [comment]
@janiskemper Happy to help🙂

**Comment by guettli** [comment]
> Looks like the lychee lint check is passing, but marking it as fail in GitHub action.

@SD-13 this is fixed on the main branch.

**Comment by SD-13** [comment]
@guettli Thanks for fixing the lint check, now CI looks green!

**Comment by janiskemper** [comment]
@guettli can you review / approve?

**Review by guettli — APPROVED** [review]
lgtm

**Pull request merged**
