### PR TITLE
:book: Update README.md

### PR DESCRIPTION
**Pull request by Sayanta66**
**What this PR does / why we need it**:

Restructuring of the documentation index.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [x] include documentation
- [ ] add unit tests

### CODE REVIEW

**Review by janiskemper — CHANGES_REQUESTED** [review]
I think we shouldn't remove the link to CAPI without having anything equivalent!

**Comment by Sayanta66** [comment]
> I think we shouldn't remove the link to CAPI without having anything equivalent!

So, do you want to add a description before `Quickstart` about the importance of CAPI quickstart in CAPH documentation, and then index the doc in this way?

**Comment by janiskemper** [comment]
Yes I think you should only remove this reference if we have another one of some sort. You can add a sentence about CAPI before that

**Comment by Sayanta66** [comment]
I just updated the index doc. Have a look. I think this one is looking better now.

**Review by janiskemper — COMMENTED** [review]
yes, looks good. Plz squash now!

**Pull request closed without merging**
