### PR TITLE
📖 added two hyperlink to hcould-variables

### PR DESCRIPTION
**Pull request by guettli**
**What type of PR is this?**

/kind documentation     Adds documentation.

### CODE REVIEW

**Comment by batistein** [comment]
Thank your very much! Only some minor things:
- Please change the PR Title wit `:book:` as a prefix. [Read more here.](https://github.com/syself/cluster-api-provider-hetzner/blob/main/CONTRIBUTING.md) This is needed for the automatic release notes generation.
- I think it's better if we name it something like HCLOUD_X_MACHINE_TYPE or MACHINE_TYPE
- If possible please change all the four list items to an unordered list or leave a new line so they are on top of each other

**Comment by guettli** [comment]
@batistein I updated the PR. Feel free to change it, if there are still small things to change.

**Comment by batistein** [comment]
Thank you very much it looks fine now! It needs only a squashing of commits. Please see: https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

**Comment by guettli** [comment]
> Thank you very much it looks fine now! It needs only a squashing of commits. Please see: https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

squashed.

**Pull request merged**
